# Generated by Django 2.2.1 on 2019-09-05 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('option_1', models.CharField(max_length=50)),
                ('option_2', models.CharField(max_length=50)),
                ('option_3', models.CharField(max_length=50)),
                ('option_4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExamProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(choices=[('Exam 1', 'Exam 1'), ('Exam 2', 'Exam 2')], max_length=20)),
                ('start_time', models.TimeField(auto_now=True)),
                ('end_time', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('active_status', models.BooleanField(default=False)),
                ('exam_question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_question', to='exam_system.Questions')),
                ('exam_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_profile', to='custom_users.Profile')),
            ],
        ),
    ]
