# Generated by Django 2.2.1 on 2019-09-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examprocess',
            options={'ordering': ['-id'], 'verbose_name_plural': 'ExamProcess'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterField(
            model_name='examprocess',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='examprocess',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
